import { mkdir, readFile, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const packageJson = JSON.parse(
  await readFile(new URL("package.json", root), "utf8"),
);
const metadataTemplate = await readFile(
  new URL("src/metadata.txt", root),
  "utf8",
);
const metadata = metadataTemplate.replace(
  /^\/\/ @version\s+.*$/m,
  `// @version      ${packageJson.version}`,
);
const core = await readFile(new URL("src/core.js", root), "utf8");
const captureBridge = await readFile(
  new URL("src/capture-bridge.js", root),
  "utf8",
);
const main = await readFile(new URL("src/main.js", root), "utf8");
const bundledCore = core.replaceAll(/^export /gm, "");
const bundledCaptureBridge = captureBridge
  .replaceAll(/^import .*;$/gm, "")
  .replaceAll(/^export /gm, "");
const output = [
  metadata.trim(),
  "",
  "// Generated from src/. Do not edit this file directly.",
  "(() => {",
  '"use strict";',
  "",
  bundledCore,
  "",
  bundledCaptureBridge,
  "",
  main,
  "})();",
  "",
].join("\n");

await mkdir(new URL("dist/", root), { recursive: true });
await writeFile(new URL("dist/inventory-gift.user.js", root), output);
